import { connectDB } from '../config/db.js';
import { Service } from '../models/services.model.js';
import { Doctor } from '../models/doctors.model.js';
import mongoose from 'mongoose';

async function seed() {
  await connectDB();

  await Service.deleteMany({});
  await Doctor.deleteMany({});

  const services = await Service.insertMany([
    {
      name: 'Dental Implants',
      slug: 'dental-implants',
      category: 'Surgical',
      shortDescription: 'Permanent tooth replacement with a natural look and feel.',
      description: 'Titanium dental implants that replace missing teeth with a strong, natural-looking solution.',
      priceFrom: 1200,
      durationMinutes: 90,
    },
    {
      name: 'Teeth Whitening',
      slug: 'teeth-whitening',
      category: 'Cosmetic',
      shortDescription: 'Professional in-office whitening for a brighter smile.',
      description: 'Professional whitening treatment that removes stains and brightens teeth by several shades.',
      priceFrom: 250,
      durationMinutes: 45,
    },
    {
      name: 'Routine Cleaning',
      slug: 'routine-cleaning',
      category: 'General',
      shortDescription: 'Standard cleaning and dental examination.',
      description: 'Routine cleaning removes plaque, tartar, and helps prevent gum disease.',
      priceFrom: 80,
      durationMinutes: 30,
    },
    {
      name: 'Root Canal Treatment',
      slug: 'root-canal-treatment',
      category: 'Surgical',
      shortDescription: 'Save infected teeth without extraction.',
      description: 'Removes infected pulp, disinfects canals, and restores the tooth.',
      priceFrom: 450,
      durationMinutes: 90,
    },
    {
      name: 'Dental Crown',
      slug: 'dental-crown',
      category: 'General',
      shortDescription: 'Restore damaged teeth with durable crowns.',
      description: 'Custom ceramic crowns restore strength, function, and appearance.',
      priceFrom: 650,
      durationMinutes: 75,
    },
    {
      name: 'Dental Veneers',
      slug: 'dental-veneers',
      category: 'Cosmetic',
      shortDescription: 'Transform your smile with porcelain veneers.',
      description: 'Thin porcelain shells placed over teeth for a beautiful smile makeover.',
      priceFrom: 900,
      durationMinutes: 120,
    },
    {
      name: 'Braces Consultation',
      slug: 'braces-consultation',
      category: 'General',
      shortDescription: 'Comprehensive orthodontic assessment.',
      description: 'Consultation to evaluate bite alignment and recommend treatment options.',
      priceFrom: 100,
      durationMinutes: 40,
    },
    {
      name: 'Invisalign',
      slug: 'invisalign',
      category: 'Cosmetic',
      shortDescription: 'Clear aligners for teeth straightening.',
      description: 'Custom clear aligners designed to gradually straighten teeth.',
      priceFrom: 2800,
      durationMinutes: 60,
    },
    {
      name: 'Tooth Extraction',
      slug: 'tooth-extraction',
      category: 'Surgical',
      shortDescription: 'Safe removal of damaged or impacted teeth.',
      description: 'Simple and surgical tooth extraction procedures with local anesthesia.',
      priceFrom: 200,
      durationMinutes: 45,
    },
    {
      name: 'Pediatric Dental Checkup',
      slug: 'pediatric-dental-checkup',
      category: 'General',
      shortDescription: 'Comprehensive dental care for children.',
      description: 'Routine dental examination, cleaning, and preventive treatments for children.',
      priceFrom: 90,
      durationMinutes: 30,
    },
    {
      name: 'Emergency Dental Care',
      slug: 'emergency-dental-care',
      category: 'Surgical',
      shortDescription: 'Immediate treatment for dental emergencies.',
      description: 'Emergency care for severe tooth pain, broken teeth, infections, and trauma.',
      priceFrom: 180,
      durationMinutes: 60,
    },
    {
      name: 'Deep Teeth Cleaning',
      slug: 'deep-teeth-cleaning',
      category: 'General',
      shortDescription: 'Advanced cleaning for healthier gums.',
      description: 'Deep scaling and root planing to treat gum disease and maintain oral health.',
      priceFrom: 350,
      durationMinutes: 60,
    },
    {
      name: 'Smile Makeover Consultation',
      slug: 'smile-makeover-consultation',
      category: 'Cosmetic',
      shortDescription: 'Personalized smile enhancement consultation.',
      description: 'Comprehensive consultation to create a customized cosmetic dentistry treatment plan.',
      priceFrom: 150,
      durationMinutes: 45,
    },
    {
      name: 'Dental Filling',
      slug: 'dental-filling',
      category: 'General',
      shortDescription: 'Repair cavities using tooth-colored fillings.',
      description: 'Composite fillings restore decayed teeth while maintaining a natural appearance.',
      priceFrom: 120,
      durationMinutes: 40,
    },
    {
      name: 'Wisdom Tooth Removal',
      slug: 'wisdom-tooth-removal',
      category: 'Surgical',
      shortDescription: 'Removal of impacted wisdom teeth.',
      description: 'Surgical extraction of wisdom teeth to prevent pain and future complications.',
      priceFrom: 500,
      durationMinutes: 90,
    },
  ]);

  await Doctor.insertMany([
    {
      name: 'Dr. Sarah Chen',
      specialty: 'Orthodontist',
      bio: 'Dr. Sarah Chen is a board-certified orthodontist with a passion for creating beautiful, confident smiles. She specializes in Invisalign and traditional braces for patients of all ages.',
      photoUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=500&fit=crop',
      rating: 4.9,
      reviews: 124,
      experience: '12 Years Experience',
      education: 'DDS, Harvard Medical School',
      languages: ['English', 'Spanish'],
      services: [services[6]._id, services[7]._id, services[1]._id],
      workingHours: [
        { day: 'monday', startTime: '09:00', endTime: '17:00' },
        { day: 'wednesday', startTime: '09:00', endTime: '17:00' },
        { day: 'friday', startTime: '09:00', endTime: '14:00' },
      ],
      slotDurationMinutes: 30,
    },
    {
      name: 'Dr. James Okafor',
      specialty: 'General Dentist',
      bio: 'Dr. James Okafor provides comprehensive general dentistry services with a focus on preventive care and patient education. He believes in building long-term relationships with his patients.',
      photoUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=500&fit=crop',
      rating: 5.0,
      reviews: 89,
      experience: '15 Years Experience',
      education: 'MDS, Stanford University',
      languages: ['English', 'French'],
      services: [services[2]._id, services[10]._id, services[8]._id],
      workingHours: [
        { day: 'tuesday', startTime: '10:00', endTime: '18:00' },
        { day: 'thursday', startTime: '10:00', endTime: '18:00' },
        { day: 'saturday', startTime: '09:00', endTime: '13:00' },
      ],
      slotDurationMinutes: 30,
    },
    {
      name: 'Dr. Emily Rodriguez',
      specialty: 'Cosmetic Dentist',
      bio: 'Dr. Emily Rodriguez is a renowned cosmetic dentist with a reputation for creating stunning smile makeovers. She specializes in veneers, teeth whitening, and full-mouth restorations.',
      photoUrl: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&h=500&fit=crop',
      rating: 4.9,
      reviews: 210,
      experience: '18 Years Experience',
      education: 'DDS, Yale University',
      languages: ['English', 'Mandarin'],
      services: [services[1]._id, services[5]._id, services[4]._id],
      workingHours: [
        { day: 'monday', startTime: '11:00', endTime: '18:00' },
        { day: 'tuesday', startTime: '09:00', endTime: '17:00' },
        { day: 'thursday', startTime: '09:00', endTime: '17:00' },
      ],
      slotDurationMinutes: 45,
    },
    {
      name: 'Dr. Michael Johnson',
      specialty: 'Oral Surgeon',
      bio: 'Dr. Michael Johnson is an experienced oral and maxillofacial surgeon specializing in wisdom teeth extraction, dental implants, and corrective jaw surgery.',
      photoUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=500&fit=crop',
      rating: 4.7,
      reviews: 143,
      experience: '14 Years Experience',
      education: 'MD, DDS, Columbia University',
      languages: ['English', 'Korean'],
      services: [services[0]._id, services[8]._id, services[3]._id],
      workingHours: [
        { day: 'wednesday', startTime: '08:00', endTime: '16:00' },
        { day: 'friday', startTime: '08:00', endTime: '16:00' },
      ],
      slotDurationMinutes: 60,
    },
    {
      name: 'Dr. Olivia Brown',
      specialty: 'Pediatric Dentist',
      bio: 'Dr. Olivia Brown creates a fun and welcoming environment for children. She specializes in pediatric dentistry and helps kids develop healthy oral hygiene habits early.',
      photoUrl: 'https://images.unsplash.com/photo-1591604021695-0c69b7c05981?w=400&h=500&fit=crop',
      rating: 4.9,
      reviews: 178,
      experience: '10 Years Experience',
      education: 'DMD, UCLA School of Dentistry',
      languages: ['English', 'Spanish'],
      services: [services[9]._id, services[2]._id],
      workingHours: [
        { day: 'monday', startTime: '09:00', endTime: '15:00' },
        { day: 'wednesday', startTime: '09:00', endTime: '15:00' },
        { day: 'friday', startTime: '09:00', endTime: '15:00' },
      ],
      slotDurationMinutes: 30,
    },
    {
      name: 'Dr. Ahmed Hassan',
      specialty: 'Periodontist',
      bio: 'Dr. Ahmed Hassan is a specialist in periodontics and implantology. He is dedicated to saving natural teeth and restoring oral health through advanced surgical techniques.',
      photoUrl: 'https://images.unsplash.com/photo-1607990283143-e81e7a2c93ab?w=400&h=500&fit=crop',
      rating: 4.8,
      reviews: 156,
      experience: '8 Years Experience',
      education: 'DMD, University of Miami',
      languages: ['English', 'Portuguese'],
      services: [services[11]._id, services[0]._id, services[4]._id],
      workingHours: [
        { day: 'tuesday', startTime: '08:30', endTime: '16:30' },
        { day: 'thursday', startTime: '08:30', endTime: '16:30' },
      ],
      slotDurationMinutes: 45,
    },
    {
      name: 'Dr. Sophia Williams',
      specialty: 'Endodontist',
      bio: 'Dr. Sophia Williams is a root canal specialist who uses advanced technology to provide comfortable and efficient endodontic treatments. She is dedicated to saving natural teeth.',
      photoUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400&h=500&fit=crop',
      rating: 4.8,
      reviews: 132,
      experience: '11 Years Experience',
      education: 'DDS, University of Michigan',
      languages: ['English', 'German'],
      services: [services[3]._id, services[4]._id],
      workingHours: [
        { day: 'monday', startTime: '10:00', endTime: '17:00' },
        { day: 'friday', startTime: '10:00', endTime: '17:00' },
      ],
      slotDurationMinutes: 60,
    },
    {
      name: 'Dr. Robert Johnson',
      specialty: 'Prosthodontist',
      bio: 'Dr. Robert Johnson specializes in complex restorative and prosthetic dentistry. He creates natural-looking crowns, bridges, and dentures that restore function and aesthetics.',
      photoUrl: 'https://images.unsplash.com/photo-1637059824899-a441006a6875?w=400&h=500&fit=crop',
      rating: 4.9,
      reviews: 167,
      experience: '20 Years Experience',
      education: 'DDS, University of Pennsylvania',
      languages: ['English', 'Italian'],
      services: [services[4]._id, services[0]._id, services[12]._id],
      workingHours: [
        { day: 'tuesday', startTime: '09:00', endTime: '17:00' },
        { day: 'wednesday', startTime: '09:00', endTime: '17:00' },
        { day: 'saturday', startTime: '10:00', endTime: '14:00' },
      ],
      slotDurationMinutes: 45,
    },
    {
      name: 'Dr. Chloe Dubois',
      specialty: 'Orthodontist',
      bio: 'Dr. Chloe Dubois is passionate about high-tech orthodontics, utilizing digital mapping to craft seamless aligner pathways and traditional tracking styles for children and adults.',
      photoUrl: 'https://images.unsplash.com/photo-1594824813573-246434de83fb?w=400&h=500&fit=crop',
      rating: 4.6,
      reviews: 94,
      experience: '9 Years Experience',
      education: 'DDS, McGill University',
      languages: ['English', 'French'],
      services: [services[6]._id, services[7]._id],
      workingHours: [
        { day: 'tuesday', startTime: '09:00', endTime: '16:00' },
        { day: 'thursday', startTime: '09:00', endTime: '16:00' },
      ],
      slotDurationMinutes: 30,
    },
    {
      name: 'Dr. Marcus Vance',
      specialty: 'Oral Surgeon',
      bio: 'Dr. Marcus Vance brings precise structural focus to heavy extractions and dental implants. He leads complex surgical reconstructions with tailored post-care programs.',
      photoUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&h=500&fit=crop',
      rating: 4.9,
      reviews: 188,
      experience: '16 Years Experience',
      education: 'DDS, Johns Hopkins University',
      languages: ['English'],
      services: [services[0]._id, services[14]._id, services[10]._id],
      workingHours: [
        { day: 'monday', startTime: '08:00', endTime: '15:00' },
        { day: 'thursday', startTime: '08:00', endTime: '17:00' },
      ],
      slotDurationMinutes: 60,
    },
    {
      name: 'Dr. Priya Patel',
      specialty: 'General Dentist',
      bio: 'Dr. Priya Patel combines empathetic dental approaches with progressive preventive care. Her daily focus centers around comfortable routine maintenance and aesthetic fillings.',
      photoUrl: 'https://images.unsplash.com/photo-1614608682850-e0d6ed316d47?w=400&h=500&fit=crop',
      rating: 4.8,
      reviews: 112,
      experience: '7 Years Experience',
      education: 'BDS, King\'s College London',
      languages: ['English', 'Hindi', 'Gujarati'],
      services: [services[2]._id, services[13]._id, services[11]._id],
      workingHours: [
        { day: 'wednesday', startTime: '09:00', endTime: '17:00' },
        { day: 'friday', startTime: '09:00', endTime: '17:00' },
        { day: 'saturday', startTime: '08:00', endTime: '12:00' },
      ],
      slotDurationMinutes: 30,
    },
    {
      name: 'Dr. Alexander Novak',
      specialty: 'Cosmetic Dentist',
      bio: 'Dr. Alexander Novak transforms clinical dentistry into creative art. Specializing in minimal-prep custom porcelain veneers and laser brightness upgrades.',
      photoUrl: 'https://images.unsplash.com/photo-1622902046580-2b47f47f0471?w=400&h=500&fit=crop',
      rating: 4.9,
      reviews: 245,
      experience: '13 Years Experience',
      education: 'DDS, NYU College of Dentistry',
      languages: ['English', 'Russian'],
      services: [services[1]._id, services[5]._id, services[12]._id],
      workingHours: [
        { day: 'monday', startTime: '10:00', endTime: '19:00' },
        { day: 'wednesday', startTime: '10:00', endTime: '19:00' },
      ],
      slotDurationMinutes: 45,
    },
    {
      name: 'Dr. Lucas Gallagher',
      specialty: 'Endodontist',
      bio: 'Dr. Lucas Gallagher targets pain-free endodontic therapy using micro-dentistry tools. He treats microscopic fractures and saves complex compromised root configurations.',
      photoUrl: 'https://images.unsplash.com/photo-1582750433449-64c676f49f40?w=400&h=500&fit=crop',
      rating: 4.7,
      reviews: 76,
      experience: '6 Years Experience',
      education: 'DMD, Boston University',
      languages: ['English'],
      services: [services[3]._id, services[10]._id],
      workingHours: [
        { day: 'tuesday', startTime: '08:00', endTime: '16:00' },
        { day: 'friday', startTime: '08:00', endTime: '15:00' },
      ],
      slotDurationMinutes: 60,
    },
    {
      name: 'Dr. Elena Rostova',
      specialty: 'Pediatric Dentist',
      bio: 'Dr. Elena Rostova makes scary dental tools look like toys. Her custom behavioral pacing techniques guarantee tear-free cleanings and early structural cavity checks.',
      photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=500&fit=crop',
      rating: 5.0,
      reviews: 194,
      experience: '11 Years Experience',
      education: 'DDS, University of Toronto',
      languages: ['English', 'Ukrainian'],
      services: [services[9]._id, services[2]._id, services[13]._id],
      workingHours: [
        { day: 'tuesday', startTime: '09:00', endTime: '16:00' },
        { day: 'thursday', startTime: '09:00', endTime: '16:00' },
        { day: 'saturday', startTime: '09:00', endTime: '14:00' },
      ],
      slotDurationMinutes: 30,
    },
    {
      name: 'Dr. Yusuf Al-Mansoor',
      specialty: 'Periodontist',
      bio: 'Dr. Yusuf Al-Mansoor targets complex gum pocket treatments and deep osseous grafting, restoring structural bone loss caused by aggressive advancements of periodontal conditions.',
      photoUrl: 'https://images.unsplash.com/photo-1625498542602-6bfb30f39b3f?w=400&h=500&fit=crop',
      rating: 4.8,
      reviews: 103,
      experience: '10 Years Experience',
      education: 'DMD, Tufts University',
      languages: ['English', 'Arabic'],
      services: [services[11]._id, services[8]._id],
      workingHours: [
        { day: 'monday', startTime: '08:30', endTime: '16:30' },
        { day: 'wednesday', startTime: '08:30', endTime: '16:30' },
      ],
      slotDurationMinutes: 45,
    },
    {
      name: 'Dr. Natalie Vance',
      specialty: 'Prosthodontist',
      bio: 'Dr. Natalie Vance structures comprehensive occlusal bite adjustments, designing permanent implant crowns and beautiful hybrid restorations that feel perfectly natural.',
      photoUrl: 'https://images.unsplash.com/photo-1591604021695-0c69b7c05981?w=400&h=500&fit=crop',
      rating: 4.9,
      reviews: 137,
      experience: '14 Years Experience',
      education: 'DDS, University of Washington',
      languages: ['English'],
      services: [services[4]._id, services[0]._id, services[12]._id],
      workingHours: [
        { day: 'wednesday', startTime: '09:00', endTime: '17:00' },
        { day: 'thursday', startTime: '09:00', endTime: '17:00' },
        { day: 'friday', startTime: '09:00', endTime: '16:00' },
      ],
      slotDurationMinutes: 45,
    },
    {
      name: 'Dr. Kenji Tanaka',
      specialty: 'General Dentist',
      bio: 'Dr. Kenji Tanaka values direct honesty and minimally invasive drill protocols. Known for seamless composite matching on direct multi-surface functional fillings.',
      photoUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&h=500&fit=crop',
      rating: 4.7,
      reviews: 82,
      experience: '9 Years Experience',
      education: 'DDS, Osaka University',
      languages: ['English', 'Japanese'],
      services: [services[2]._id, services[13]._id, services[10]._id],
      workingHours: [
        { day: 'monday', startTime: '09:00', endTime: '18:00' },
        { day: 'tuesday', startTime: '09:00', endTime: '18:00' },
      ],
      slotDurationMinutes: 30,
    },
    {
      name: 'Dr. Simone Gatti',
      specialty: 'Cosmetic Dentist',
      bio: 'Dr. Simone Gatti constructs customized celebrity grade transformations. Her unique style utilizes rapid clinical whitening and state of the art ultra thin composite veneers.',
      photoUrl: 'https://images.unsplash.com/photo-1614608682850-e0d6ed316d47?w=400&h=500&fit=crop',
      rating: 4.9,
      reviews: 312,
      experience: '22 Years Experience',
      education: 'DMD, University of Milan',
      languages: ['English', 'Italian'],
      services: [services[1]._id, services[5]._id, services[12]._id],
      workingHours: [
        { day: 'thursday', startTime: '10:00', endTime: '20:00' },
        { day: 'friday', startTime: '10:00', endTime: '17:00' },
      ],
      slotDurationMinutes: 45,
    },
    {
      name: 'Dr. Christopher Lee',
      specialty: 'Oral Surgeon',
      bio: 'Dr. Christopher Lee executes complicated wisdom extractions and anchors durable titanium frameworks under continuous gentle sedation practices for maximal patient ease.',
      photoUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=500&fit=crop',
      rating: 4.8,
      reviews: 165,
      experience: '13 Years Experience',
      education: 'MD, DDS, UC San Francisco',
      languages: ['English', 'Mandarin'],
      services: [services[0]._id, services[14]._id, services[8]._id],
      workingHours: [
        { day: 'tuesday', startTime: '07:30', endTime: '16:00' },
        { day: 'wednesday', startTime: '07:30', endTime: '16:00' },
      ],
      slotDurationMinutes: 60,
    },
    {
      name: 'Dr. Hannah Abas',
      specialty: 'General Dentist',
      bio: 'Dr. Hannah Abas delivers highly detailed primary oral evaluations. She specializes in handling high-anxiety emergency walk-ins, providing prompt stabilization and gentle emergency options.',
      photoUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=500&fit=crop',
      rating: 4.9,
      reviews: 97,
      experience: '8 Years Experience',
      education: 'DDS, University of Jordan',
      languages: ['English', 'Arabic'],
      services: [services[2]._id, services[10]._id, services[13]._id],
      workingHours: [
        { day: 'thursday', startTime: '09:00', endTime: '18:00' },
        { day: 'saturday', startTime: '09:00', endTime: '16:00' },
      ],
      slotDurationMinutes: 30,
    },
  ]);

  console.log('[seed] done: 15 services, 20 doctors created');
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error('[seed] failed:', err);
  process.exit(1);
});